### ISSUE TITLE
center: false doesnt work in yalm header in slide mode

### ISSUE THREAD

**Issue by SPyofgame200** [hackmdio/hackmd-io-issues#276]

**Comment by SPyofgame200** [comment]
I am using linux and this happen on hackmd, tried this but doesnt work (confirm that there is no blank or non-sense line on top of yalm)

```css
---
tags: Template
title: Problem_name
author: Editorial-Slayers Team
license: Public domain
slideOptions:
  theme: solarized
  transition: 'fade'
  center: false
---


<style>
    .markdown-body { max-width: 2048px; }
</style>

$\Huge \text{🌱 Problem_name}$

###### 🔗 Link: [Link](URL)
###### 📌 Tags: 
###### 👤 Writter: @SPyofgame 
###### 👥 Contributor: [@](https://codeforces.com/profile/)
###### 📋 Content:

[TOC]

...
```
