### ISSUE TITLE
Odd margins on the right side of notes

### ISSUE THREAD

**Issue by cyrneko** [hackmdio/hackmd-io-issues#303]
### Is this a hackmd.io issue?

- [X] Yes, the bug happens on https://hackmd.io
- [ ] No. If it's a self-hosted CodiMD instance, please fire up the issue in the repo of CodiMD: https://github.com/hackmdio/codimd

### What's the problem

Margins on the right side of the screen look quite off, especially on mobile devices.
to fix this, I've started adding this little snippet of CSS at the top of my notes (seen [here](https://hackmd.io/@TGRush/SJO3zc8Pc)):

```css
.markdown-body {
    margin-right: auto!important;
}
```

#### Current behaviour

<img src="https://user-images.githubusercontent.com/58338843/175144224-f8d21979-33c4-42a2-baf5-f6e52c8ad53a.png" width=250>

Provide steps to reproduce:

1. Go to Any HackMD Note
2. Resize the window to be smaller, or view it on an Android or iOS phone
3. See the odd margins

The tutorial notes and such will work fine for portraying this:
https://hackmd.io/features _← This works just fine for the purpose of portraying this minor issue_

#### Expected behaviour

I expect the margin on the left and right hand side to be exactly the same, not only for visuals, but also consistency

#### Environment

I use HackMD on:

**Desktop**
- OS: Pop!_OS 22.04
- Browser: Firefox 
- Browser Version: 101

**Mobile**
- Device: OnePlus 5T
- OS: Lineage 19.1 - Android 12.1
- Browser: Bromite _(for the purpose of this bug report, it's identical to Chromium)_
- Version: 102.0

**Comment by ZebraAlgebra** [comment]
I also found this to be odd (in terms of layout).

For the reason why there are white spaces, my guess is that the margin is reserved for comment tags.

As a quick fix, if you add the following to your css settings:
```css
#doc.comment-enabled.comment-inner {
    margin-right: 0;
    }
#doc.comment-enabled.comment-open-inner {
    margin-right: 0;
}
```
then this should remove the weird margin; I don't know if this causes other issues so far.
